name: pt1_rodriguez_pau
description: Segunda práctica de Flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
cupertino_icons: ^1.0.2
google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
